name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4

      - name: Start Supabase local development setup
        working-directory: ./packages/backend
        run: supabase start

      - name: Prepare env
        working-directory: ./packages/backend
        run: |
          supabase status -o yaml | while IFS=: read -r key value; do echo SUPABASE_"$key"=$(echo "$value" | sed 's/^ *//') >> $GITHUB_ENV; done
  verify-backend:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4

      - name: Start Supabase local development setup
        working-directory: ./packages/backend
        run: supabase start

      - name: Verify generated types are checked in
        working-directory: ./packages/backend
        run: |
          supabase gen types typescript --local > types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
      - name: Execute API-tests
        working-directory: ./packages/backend
        run: |
          env
          npm i
          npm t
